[package]
name = "rac_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = "1.8"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
