[record.LockRecordRaw]
derive = ["Debug", "Serialize", "Clone"]
fields = [
  { name = "connection", type = "uuid", version = "11.0" },
  { name = "descr", type = "lock_descr", version = "11.0" },
  { name = "locked_at", type = "datetime_u64_be", version = "11.0" },
  { name = "session", type = "uuid", version = "11.0" },
  { name = "object", type = "uuid", version = "11.0" },
]

[rpc.LockList]
derive = ["Debug", "Clone"]
fields = [
  { name = "cluster", type = "uuid", version = "11.0" },
]
version = "11.0"
method_req = 0x48
method_resp = 0x49
requires_cluster_context = true
requires_infobase_context = false

[response.LockList]
body = { type = "list_u8", item = "LockRecordRaw" }
