[record.ProcessLicense]
derive = ["Debug", "Serialize", "Default", "Clone"]
fields = [
  { name = "_gap_license_0", type = "u8", skip = true },
  { name = "file_name", type = "str8" },
  { name = "full_presentation", type = "str_u14" },
  { name = "issued_by_server", type = "u8_bool" },
  { name = "license_type", type = "u32_be" },
  { name = "max_users_all", type = "u32_be" },
  { name = "max_users_current", type = "u32_be" },
  { name = "network_key", type = "u8_bool" },
  { name = "server_address", type = "str8" },
  { name = "process_id", type = "str8" },
  { name = "server_port", type = "u32_be" },
  { name = "key_series", type = "str8" },
  { name = "brief_presentation", type = "str8" },
]

[record.ProcessRecord]
derive = ["Debug", "Serialize", "Clone"]
fields = [
  { name = "process", type = "uuid" },
  { name = "_gap_0", type = "bytes", len = 8, skip = true },
  { name = "avg_call_time", type = "f64_be" },
  { name = "avg_db_call_time", type = "f64_be" },
  { name = "avg_lock_call_time", type = "f64_be" },
  { name = "avg_server_call_time", type = "f64_be" },
  { name = "avg_threads", type = "f64_be" },
  { name = "capacity", type = "u32_be" },
  { name = "connections", type = "u32_be" },
  { name = "host", type = "str8" },
  { name = "licenses", type = "list_u8", item = "ProcessLicense" },
  { name = "port", type = "u16_be" },
  { name = "memory_excess_time", type = "u32_be" },
  { name = "memory_size", type = "u32_be" },
  { name = "pid", type = "str8" },
  { name = "use_status", type = "u32_be" },
  { name = "selection_size", type = "u32_be" },
  { name = "started_at", type = "datetime_u64_be" },
  { name = "running", type = "u32_be_bool" },
  { name = "available_performance", type = "u32_be" },
  { name = "reserve", type = "u8_bool" },
  { name = "turned_on", type = "computed", computed = "ne_zero", source = "use_status", rust_type = "bool" },
]
